default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shopping_mall_dev

test:
  <<: *default
  database: shopping_mall_test


production:
  <<: *default
  database: shopping_mall_production
  username: shopping_mall
  password: <%= ENV['shopping_mall_DATABASE_PASSWORD'] %>
